/*
Combined URCS Detection Rule
Generated by URCS Investigator Toolkit
*/

rule urcs_combined_detection {
    meta:
        description = "Combined URCS detection rule"
        author = "URCS Investigator Toolkit"
        date = "2024"
        reference = "MITRE ATT&CK T1055.012, T1543.003, T1053.005, T1083"
        severity = "high"
    
    strings:
        // Initial drop indicators
        $chrome_update = "Chrome_update.exe" nocase
        $powershell_download = "Invoke-WebRequest" nocase
        
        // Self-copy indicators
        $color_dir = "\System32\spool\drivers\color\" nocase
        $random_exe = /[a-z]{8}\.exe/ nocase
        
        // Registry persistence indicators
        $ctfmon = "ctfmon" nocase
        $run_key = "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" nocase
        
        // Service persistence indicators
        $gupdatem = "gupdatem" nocase
        $google_update = "Google Update Service" nocase
        
        // Scheduled task indicators
        $ddriver = "Ddriver" nocase
        $scheduled_task = "schtasks" nocase
        
        // Process injection indicators
        $rundll32 = "rundll32.exe" nocase
        $explorer = "explorer.exe" nocase
        
        // Network beacon indicators
        $api_ipify = "api.ipify.org" nocase
        $moneroocean = "gulf.moneroocean.stream" nocase
        $stratum = "stratum+tcp://" nocase
        
        // Self-deletion indicators
        $remove_item = "Remove-Item" nocase
        $my_invocation = "$MyInvocation.MyCommand.Path" nocase
        
        // Obfuscation indicators
        $high_entropy = /[\x00-\xff]{100,}/  // High entropy pattern
        
    condition:
        uint16(0) == 0x5A4D and 
        (
            // Initial drop
            (all of ($chrome_update, $powershell_download)) or
            
            // Self-copy
            (all of ($color_dir, $random_exe)) or
            
            // Registry persistence
            (all of ($ctfmon, $run_key)) or
            
            // Service persistence
            (all of ($gupdatem, $google_update)) or
            
            // Scheduled task
            (all of ($ddriver, $scheduled_task)) or
            
            // Process injection
            (all of ($rundll32, $explorer)) or
            
            // Network beacon
            (all of ($api_ipify, $moneroocean)) or
            
            // Self-deletion
            (all of ($remove_item, $my_invocation)) or
            
            // Obfuscation
            $high_entropy
        )
}
